#/bin/python3
import argparse
from email import message
import yaml
import sys
import os

class Port:
    def __init__(self, port_yaml):
        if isinstance(port_yaml, str):
            self.name = port_yaml
            self.kind = None
            self.message = None
        else:
            self.name, value = next(iter(port_yaml.items()))
            self.kind = value.get('kind', None)
            self.message = value.get('message', None)

class SubModule:
    def __init__(self, sm_yaml):
        if isinstance(sm_yaml, str):
            self.name = sm_yaml
            self.number = 1
        else:
            self.name, self.number = next(iter(sm_yaml.items()))

class Connection:
    def __init__(self, con_yaml):
        if 'source' in con_yaml:
            self.bi_directed = False
            self.source = con_yaml.get('source', None)
            self.target = con_yaml.get('target', None)
        else:
            self.bi_directed = True
            self.source, self.target = next(iter(con_yaml.items()))

class Parameter:
    def __init__(self, index, name, ptype, default_value = None):
        self.index = index
        self.name = name
        self.ptype = ptype
        self.default_value = default_value

# modules & built-ins
class Module:
    def __init__(self, context, yaml_data):
        self.context = context
        self.name, value = next(iter(yaml_data.items()))
        self.ports = []
        for p in value.get('ports', []):
            self.ports.append(Port(p))

        self.sub_modules = []
        for sm in value.get('subModules', []):
            self.sub_modules.append(SubModule(sm))

        self.csr_registers = value.get('csrRegiters', [])

        self.connections = []
        for con in value.get('connections', []):
            self.connections.append(Connection(con))

        if 'base' in value:
            self.base = value.get('base')
            self.parameters = value.get('parameters')
        else:
            self.base = None
            self.parameters = []

# Built-in will generate C++ template header file, requires
# to fill up detailed implementation. However, so far built-in
# works only as place-holder to helps module to inherit.
# [TODO] find way to auto fill-up/merge solution for built-in
#        template class
class BuiltIn:
    def __init__(self, context, yaml_data):
        self.context = context
        self.name, value = next(iter(yaml_data.items()))

        self.parameters = []
        if 'parameters' in value:
            for index, pa in enumerate(value.get('parameters', [])):
                pname, ptype = next(iter(pa.items()))
                self.parameters.append({'index':index, 'pname': pname, 'ptype': ptype})

        self.ports = []
        for p in value.get('ports', []):
            self.ports.append(Port(p))
            
# messages
class Message:
    def __init__(self, context, yaml_data):
        self.context = context
        self.name, value = next(iter(yaml_data.items()))

        self.fields = []
        for f in value.get('fields', []):
            mname, mtype = next(iter(f.items()))
            self.fields.append({'mname':mname, 'mtype':mtype})

# registers: csr registers and other register
class Register:
    def __init__(self, context, yaml_data):
        self.context = context
        self.name, value = next(iter(yaml_data.items()))
        self.address = value.get('address', 0x00000000)

# help infos : enum
class Enum:
    def __init__(self, context, yaml_data):
        self.context = context
        self.name, self.values = next(iter(yaml_data.items()))

# help infos : constants
class Constant:
    def __init__(self, context, yaml_data):
        self.context = context
        self.name, self.value = next(iter(yaml_data.items()))

class ModelGenerator:
    def __init__(self, yaml_data, config = {}):
        self.yaml_data = yaml_data
        self.config = config

        self.context = {}
        self._collect()

    def _collect(self):
        self._do_collect('modules', Module);
        self._do_collect('builtins', BuiltIn);
        self._do_collect('messages', Message);
        self._do_collect('registers', Register);
        self._do_collect('enums', Enum);
        self._do_collect('constants', Constant);

    def _do_collect(self, entity_name, target_clz):
        self.context[entity_name] = []
        for d in self.yaml_data.get(entity_name, []):
            self.context[entity_name].append(target_clz(self.context, d))

    FILE_HEADER = """
/* --------------------------------------------------------------------------------
* AUTOMIATIC GENERATED BY MOUDLE-GEN, DO NOT DIRECTLY MODIFY IT
* -------------------------------------------------------------------------------- */
"""

    COMMON_INCLUDE_HEADER = """
#include "include/common/register.h"
#include "include/common/enum.h"
#include "include/common/constant.h"

#include "module.h"

#include <vector>
#include <cstdint>

"""

    def generate(self):
        # init folder hierachy
        output_dir = self.config['output_dir']

        module_dir = os.path.join(output_dir, "module")
        os.makedirs(module_dir, exist_ok=True) 
        self._generateModule(module_dir);
        self._generateBuiltin(module_dir);
        self._generateMessage(module_dir);

        common_dir = os.path.join(output_dir, "common")
        os.makedirs(common_dir, exist_ok=True) 
        self._generateRegister(common_dir)
        self._generateEnum(common_dir)
        self._generateConstant(common_dir)

    def _generateModule(self, base_dir):
        for md in self.context['modules']:
            hfile = os.path.join(base_dir, f"{md.name}Base.h")
            with open(hfile, 'w', encoding='utf-8') as f:
                f.write(ModelGenerator.FILE_HEADER)
                f.write(ModelGenerator.COMMON_INCLUDE_HEADER)

                f.write(f"class {md.name} : public ")
                if md.base is None:
                    print("sc_module {{\n")
                else:
                    print(f"{md.base}<")
                    for ind, param in enumerate(md.parameters):



    def _generateBuiltin(self, base_dir):
        # [NOTE] built-in so far works only as place-holder
        #        to helps module to inherit. detailed built-in
        #        module declaration and implementation is fully
        #        out-of-yaml provided.
        pass
                

    def _generateMessage(self, base_dir):
        hfile = os.path.join(base_dir, "message.h")
        with open(hfile, 'w', encoding='utf-8') as f:
            f.write(ModelGenerator.FILE_HEADER)

            for msg in self.context['messages']:
                f.write(f"struct {msg.name} {{\n")
                for fi in msg.fields:
                    f.write(f"  {fi['mtype']} {fi['mname']};\n")
                f.write(f"}};\n\n")

    def _generateRegister(self, base_dir):
        pass

    def _generateEnum(self, base_dir):
        hfile = os.path.join(base_dir, "enum.h")
        with open(hfile, 'w', encoding='utf-8') as f:
            f.write(ModelGenerator.FILE_HEADER)

            for eu in self.context['enums']:
                f.write(f"enum class {eu.name} {{ ")
                f.write(", ".join(eu.values))
                f.write(f" }};")

    def _generateConstant(self, base_dir):
        hfile = os.path.join(base_dir, "constant.h")
        with open(hfile, 'w', encoding='utf-8') as f:
            f.write(ModelGenerator.FILE_HEADER)

            for c in self.context['constants']:
                f.write(f"#define {c.name} {c.value};\n")


class ArgumentsParser:
    def __init__(self):
        self.parser = argparse.ArgumentParser(description="Module Generator")
        self.parser.add_argument('-i', '--input', default="module-gen/module.yaml", help="Input YAML file")
        self.parser.add_argument('-o', '--output-dir', default="src/gen/include", help="Output Module Definition Path")

    def parse(self):
        return self.parser.parse_args()

def _main():
    args_parser = ArgumentsParser()
    args = args_parser.parse()

    input_file = args.input
    output_dir = args.output_dir

    # Load module from input YAML
    with open(input_file, 'r') as f:
        model_yaml = yaml.safe_load(f)

        modelgen = ModelGenerator(model_yaml, {
            'output_dir' : output_dir
        })

        modelgen.generate()

if __name__ == "__main__":
    _main()